#!/usr/bin/env python3
"""
Regenerate data/prompts.json from a structured category dictionary.

Each session = 15 sentences that *use* a vocabulary class (not just a
word list). The same English prompt often appears with a Hinglish twin
so the model learns to code-switch on demand.

Usage:
    python3 scripts/build_prompts.py           # merge (keep existing 1-9)
    python3 scripts/build_prompts.py --replace  # drop existing 10+, regenerate
    python3 scripts/build_prompts.py --per-session 18   # more lines/session
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROMPTS = ROOT / "data" / "prompts.json"

# -------------------------------------------------------------- categories
# every entry: (id, name, title, lines, manual_only?)
SESSIONS = [
    # ---------------- everyday commands (short, snappy English) ------
    (10, "alarms", "Alarms, timers, reminders", [
        "Set an alarm for six thirty in the morning.",
        "Set a timer for fifteen minutes.",
        "Remind me to call mom at eight PM.",
        "Wake me up at five forty five on weekdays.",
        "Cancel my seven AM alarm.",
        "Snooze the alarm for ten more minutes.",
        "Set a reminder for tomorrow at noon.",
        "Remind me to take my medicine after lunch.",
        "Snooze for five minutes please.",
        "How many alarms do I have set?",
        "Set a timer for twenty minutes when I start cooking.",
        "Wake me up gently at sunrise tomorrow.",
        "Set a countdown for ninety seconds.",
        "Cancel all my reminders for today.",
        "Add a daily reminder to drink water.",
    ], False),
    (11, "apps_open", "Open apps and launch programs", [
        "Open Spotify.",
        "Launch Visual Studio Code.",
        "Open the terminal please.",
        "Start a new browser window.",
        "Open my downloads folder.",
        "Launch the file manager.",
        "Open the calculator app.",
        "Start the settings window.",
        "Open the notes application.",
        "Launch the screenshot tool.",
        "Open Discord.",
        "Start the music player.",
        "Open the photo gallery.",
        "Launch the calendar app.",
        "Open the system monitor.",
    ], False),
    (12, "web_search", "Web search and quick lookups", [
        "Search for the best biryani near me.",
        "Look up the weather in Bangalore tomorrow.",
        "Find a recipe for paneer butter masala.",
        "Search for the nearest pharmacy.",
        "Look up the meaning of serendipity.",
        "Find me a hotel under three thousand rupees.",
        "Search how to fix a leaking tap.",
        "Look up the population of Tokyo.",
        "Find the cheapest flights to Goa.",
        "Search for the IPL score.",
        "Look up the meaning of the word gregarious.",
        "Find a yoga class near me.",
        "Search for the best laptop under fifty thousand.",
        "Look up the distance between Delhi and Jaipur.",
        "Find the latest news on Chandrayaan.",
    ], False),
    (13, "media_control", "Music, video and media control", [
        "Play the next track.",
        "Pause the music.",
        "Resume playback.",
        "Skip to the next song.",
        "Turn the volume up to eighty percent.",
        "Lower the volume a little.",
        "Mute the speakers.",
        "Unmute please.",
        "Repeat this song.",
        "Shuffle my playlist.",
        "Play lo-fi study music.",
        "Stop the video.",
        "Full screen the video please.",
        "Rewind thirty seconds.",
        "Fast forward to the end.",
    ], False),
    (14, "system_settings", "System settings: brightness, wifi, bluetooth", [
        "Turn on Wi-Fi.",
        "Disable Bluetooth.",
        "Set brightness to maximum.",
        "Dim the screen a little.",
        "Turn on airplane mode.",
        "Enable do not disturb.",
        "Switch to dark mode.",
        "Change the wallpaper to something minimal.",
        "Turn on battery saver.",
        "Disable notifications for an hour.",
        "Lock the screen now.",
        "Sign out and switch user.",
        "Turn off the touchpad.",
        "Enable night light.",
        "Open the sound settings.",
    ], False),
    (15, "navigation", "Navigation, directions and travel", [
        "Take me home.",
        "Navigate to the airport.",
        "How long will it take to reach the office?",
        "Find a coffee shop on the way.",
        "Avoid tolls on this route.",
        "Start navigation in walking mode.",
        "Find a petrol pump within two kilometres.",
        "Show me an alternative route.",
        "Cancel the current navigation.",
        "How far is the nearest hospital?",
        "Navigate to MG Road metro station.",
        "Find a parking spot near the mall.",
        "Take me to the nearest ATM.",
        "Drive me to Connaught Place.",
        "Show me public transport options.",
    ], False),
    (16, "calendar_meetings", "Calendar, meetings and scheduling", [
        "Schedule a meeting with Rohit at three PM tomorrow.",
        "What's on my calendar today?",
        "Move the stand-up to four PM.",
        "Cancel the call with the design team.",
        "Block my calendar from five to six today.",
        "Add a one hour event called gym at six AM.",
        "Reschedule the review to next Monday.",
        "Show me my next meeting.",
        "Create a recurring event every Tuesday at ten.",
        "Who is the first meeting with tomorrow?",
        "Send a meeting invite to Anika and Sameer.",
        "When is my next free slot today?",
        "Move all my meetings by one hour tomorrow.",
        "Set the location of the stand-up to Zoom.",
        "Add a fifteen minute buffer between meetings.",
    ], False),

    # ---------------- daily words in natural sentences --------------
    (17, "daily_objects", "Daily objects in natural sentences", [
        "Pass me the glass of water please.",
        "I can't find my wallet anywhere.",
        "The remote is on the sofa.",
        "Did you lock the front door?",
        "Hand me the umbrella, it looks like rain.",
        "Put the keys on the counter.",
        "Where did I leave my headphones?",
        "I need a charger for my phone.",
        "The torch is in the drawer.",
        "Please bring me a towel.",
        "Have you seen my reading glasses?",
        "I need a spoon for the soup.",
        "The blanket is in the cupboard.",
        "I left my watch in the bathroom.",
        "Can you grab me a pen?",
    ], False),
    (18, "family_relations", "Family relations and people", [
        "Call my sister on her mobile.",
        "Send a message to my dad.",
        "Tell mom I'll be late tonight.",
        "Video call my brother.",
        "Schedule dinner with my grandparents on Sunday.",
        "Add my cousin Priya to the family group.",
        "Book a cab for my uncle.",
        "Remind me to wish my nephew on his birthday.",
        "Send flowers to my aunt in Pune.",
        "What's my mom's phone number?",
        "Did my husband call?",
        "Forward the email to my father-in-law.",
        "Group call my parents and in-laws.",
        "Drop a text to my best friend.",
        "Wish my colleague a happy anniversary.",
    ], False),

    # ---------------- complex English (technical / advanced) -------
    (19, "complex_english_prog", "Complex English: programming terms", [
        "The function uses a recursive descent parser.",
        "I need to debug this memory leak in production.",
        "The compiler is throwing a segmentation fault.",
        "Refactor the authentication module to use OAuth two.",
        "Deploy the container to the staging environment.",
        "The build is failing because of a missing dependency.",
        "Optimise the database query with a proper index.",
        "Set up a load balancer across three availability zones.",
        "The kubernetes cluster is in a crash loop.",
        "Run the integration tests on the CI pipeline.",
        "Roll back the deployment to the previous version.",
        "Enable distributed tracing for the microservices.",
        "Compress the payload using gzip before transit.",
        "Implement rate limiting on the public API.",
        "Migrate the legacy monolith to event driven architecture.",
    ], False),
    (20, "complex_english_ai", "Complex English: AI / ML terms", [
        "Fine tune the model on the personal voice dataset.",
        "The transformer uses multi-head self attention.",
        "I need to quantize the weights to int eight for inference.",
        "Run inference with a beam size of five.",
        "The training loss is diverging, lower the learning rate.",
        "Compute the perplexity on the held out validation set.",
        "Apply LoRA adapters on the query and value projections.",
        "Tokenize the input with the sentence piece model.",
        "The embeddings are stored in a vector database.",
        "Generate the response with nucleus sampling.",
        "The gradient checkpointing reduces memory by recomputing.",
        "Distil the large model into a smaller student.",
        "Use RLHF to align the assistant with user intent.",
        "Compute the word error rate on the test set.",
        "Deploy the model behind a Triton inference server.",
    ], False),
    (21, "complex_english_science", "Complex English: science and medicine", [
        "The patient presents with acute appendicitis.",
        "Run a complete blood count immediately.",
        "The lab results show elevated creatinine levels.",
        "Schedule an MRI for next Wednesday morning.",
        "The mitochondria is the powerhouse of the cell.",
        "Photosynthesis converts carbon dioxide into glucose.",
        "The vaccine triggers an adaptive immune response.",
        "Diagnose the patient with Type Two diabetes.",
        "Prescribe a course of broad spectrum antibiotics.",
        "Monitor the blood pressure every four hours.",
        "Explain the theory of general relativity in simple terms.",
        "Newton's third law states that every action has an equal and opposite reaction.",
        "The patient needs a coronary artery bypass graft.",
        "Check the liver function test before discharge.",
        "Recommend a high protein diet for recovery.",
    ], False),
    (22, "complex_english_finance", "Complex English: finance and business", [
        "Diversify the portfolio across asset classes.",
        "The inflation rate is at a five year high.",
        "Calculate the compound interest on this principal.",
        "Hedge against currency risk with a forward contract.",
        "The quarterly earnings beat analyst expectations.",
        "What's the current yield on a ten year treasury?",
        "Submit the KYC documents for the new account.",
        "Apply for a personal loan at the lowest APR.",
        "The stock split increased liquidity dramatically.",
        "Compute the present value of future cash flows.",
        "File the GST return before the eighteenth of next month.",
        "The mutual fund outperformed its benchmark by three percent.",
        "Allocate sixty percent to equities and forty to bonds.",
        "Set up a SIP of five thousand rupees per month.",
        "The depreciation schedule needs to be recalculated.",
    ], False),

    # ---------------- companies (tech, retail, finance, Indian) -----
    (23, "companies_tech", "Tech company names", [
        "Open Google Calendar.",
        "Search on Microsoft Bing.",
        "Send a Slack message to the design channel.",
        "Log in to the Atlassian Jira dashboard.",
        "Pull the latest commit from the GitHub repository.",
        "Deploy to the Amazon Web Services production account.",
        "Open the Datadog monitoring dashboard.",
        "Check the Sentry error report.",
        "Look up the API key in the AWS secrets manager.",
        "File a ticket in the Linear workspace.",
        "Open the Figma design file.",
        "Set up a Zoom call for five PM today.",
        "Sync the contacts with the Salesforce CRM.",
        "Post an update on the Notion engineering wiki.",
        "Open the Stripe payment dashboard.",
    ], False),
    (24, "companies_indian", "Indian companies and conglomerates", [
        "Order groceries from BigBasket for tonight.",
        "Book a cab on Ola to the airport.",
        "Send a message to my team on Flipkart workspace.",
        "Order a Swiggy meal from the new restaurant.",
        "Book a Zomato table for two at eight PM.",
        "Recharge my Jio prepaid plan for two hundred rupees.",
        "Pay the Airtel broadband bill for this month.",
        "Open the Paytm wallet.",
        "Send five hundred rupees to my friend on PhonePe.",
        "Track my Flipkart order number six seven eight nine.",
        "Book an Ola Prime to MG Road.",
        "Schedule a meeting with the Tata Motors dealer.",
        "Check my HDFC bank account balance.",
        "Apply for a credit card on the ICICI website.",
        "Renew my IRCTC tatkal booking for tomorrow.",
    ], False),
    (25, "brands_consumer", "Consumer brands and products", [
        "Order a Domino's margherita pizza for dinner.",
        "Buy a Cadbury Dairy Milk on the way home.",
        "Add Nescafe classic to the shopping list.",
        "Reorder our usual Amul butter from the store.",
        "Book a Marriott hotel for the weekend trip.",
        "Find the nearest Apple service centre.",
        "Buy a Samsung Galaxy S twenty five.",
        "Pick up a Nike running shoe in size ten.",
        "Get the Adidas Ultraboost in black.",
        "Find a Sony WH-1000XM five in stock.",
        "Order a OnePlus Nord CE four.",
        "Buy a pair of Levi's five zero one jeans.",
        "Restock the Dove shampoo and conditioner.",
        "Order a BigBasket monthly grocery pack.",
        "Find the cheapest Sony Bravia fifty five inch.",
    ], False),

    # ---------------- places: Indian + world -----------------------
    (26, "places_indian", "Indian cities and landmarks", [
        "Take me to India Gate in New Delhi.",
        "Find a hotel near Charminar in Hyderabad.",
        "Navigate to Howrah Bridge in Kolkata.",
        "Take me to Marina Beach in Chennai.",
        "Book a flight from Mumbai to Bangalore.",
        "Find a restaurant near MG Road in Pune.",
        "Navigate to the Taj Mahal in Agra.",
        "Take me to the Infosys campus in Mysore.",
        "Find a cafe near Park Street in Kolkata.",
        "Book a cab to Coimbatore Junction station.",
        "Navigate to the IIT Bombay main gate.",
        "Find a hotel near Hawa Mahal in Jaipur.",
        "Take me to the airport in Goa.",
        "Find the nearest Starbucks in Bandra.",
        "Navigate to the Wankhede Stadium in Mumbai.",
    ], False),
    (27, "places_world", "World cities and landmarks", [
        "Book a flight to Tokyo next month.",
        "Find a hotel near Times Square in New York.",
        "Navigate to the Eiffel Tower in Paris.",
        "Take me to Heathrow Airport terminal five.",
        "Book a table at a restaurant near the Colosseum in Rome.",
        "Find a cafe in Shibuya, Tokyo.",
        "Navigate to the Sydney Opera House.",
        "Book a flight from London to Dubai.",
        "Find the cheapest hotel in Bali for the weekend.",
        "Navigate to the Brandenburg Gate in Berlin.",
        "Book a tour of the Pyramids of Giza.",
        "Find a restaurant near the Burj Khalifa.",
        "Take me to the Grand Canyon south rim.",
        "Navigate to the Statue of Liberty.",
        "Book a flight to Singapore for next Friday.",
    ], False),

    # ---------------- numbers, dates, currency ----------------------
    (28, "numbers_currency", "Numbers, phone numbers, currency", [
        "Transfer fifteen thousand rupees to my savings account.",
        "Set a reminder for the twenty fifth of December.",
        "Call nine eight seven six five four three two one zero.",
        "Convert two hundred US dollars to Indian rupees.",
        "Schedule a meeting for the fourteenth of March at four PM.",
        "What is two thousand five hundred plus three thousand seven fifty?",
        "Set an alarm for seven forty five AM.",
        "How much is one Bitcoin in dollars today?",
        "Send nine thousand nine hundred ninety nine rupees to my friend.",
        "Book tickets for two adults and one child.",
        "The flight leaves at twenty three thirty on the fifteenth.",
        "Calculate eighteen percent GST on twelve thousand.",
        "Dial plus nine one nine eight seven six five four three two one zero.",
        "Add the numbers four five six and seven eight nine.",
        "What's the date twenty days from today?",
    ], False),

    # ---------------- Hinglish: daily ------------------------------
    (29, "hinglish_daily", "Hinglish daily commands", [
        "Yaar, alarm laga do subah chhe baje.",
        "Aaj mausam kaisa hai, bata do.",
        "Bhai, ek chai banake de sakte ho?",
        "Subah jaldi uthna hai, ek reminder laga do.",
        "Ghar kaun aaya hai, check karo please.",
        "Bhai ka phone laga do, important call hai.",
        "Mummy ko bol do main ghar aa raha hoon.",
        "Chai mein cheeni kam daalna please.",
        "Dukaan se doodh le aana yaad rakhna.",
        "Dinner mein kya banega aaj?",
        "Kapde dhul gaye kya, dekhna please.",
        "Aaj gym jaana hai, time batao.",
        "Acha suno, ek kaam karna tha.",
        "Mujhe thoda pani chahiye abhi.",
        "Office kaunse time pe niklna hai?",
    ], True),
    (30, "hinglish_food", "Hinglish: food and cooking", [
        "Paneer butter masala ki recipe bata do.",
        "Biryani mein kitna time lagega banne mein?",
        "Maggi banao, yaar, bhookh lag rahi hai.",
        "Roti ke liye aata kitna chahiye?",
        "Dinner mein dal chawal banao aaj.",
        "Chai adrak wali bana do, thodi strong.",
        "Aloo ki sabzi mein mirchi kam daalna.",
        "Cake bake karna hai, oven preheat kar do.",
        "Curd khatam ho gaya, list mein daal do.",
        "Breakfast mein poha banana hai.",
        "Idli batter ready hai, dosa banao.",
        "Lassi meethi banao thodi.",
        "Palak paneer ki sabzi mein kitni palak chahiye?",
        "Khichdi banao aaj dinner ke liye.",
        "Egg omelette banao, desi style.",
    ], True),
    (31, "hinglish_travel", "Hinglish: travel and directions", [
        "Airport tak kitna time lagega, yaar?",
        "Auto wala kahan milega yahan se?",
        "Train platform number kya hai Patna ki?",
        "Bus stand kaise jayein yahan se?",
        "Petrol pump paas mein kahan hai?",
        "Hotel book karna hai Bangalore mein, acha sa.",
        "Flight late hai kya? Check karo please.",
        "Ola book kar do airport tak.",
        "Taxi wala zyada paisa maang raha hai.",
        "Map pe dikha do kahan hai hum abhi.",
        "Metro station kaise jaate hain yahan se?",
        "Auto meter se chalao please.",
        "Bhai, ghar ka raasta bata do.",
        "Station pe pahunchne mein time lagega kya?",
        "Yeh address sahi hai kya, verify karo.",
    ], True),

    # ---------------- Hinglish complex: code/dev/AI ---------------
    (32, "hinglish_code_dev", "Hinglish × tech: dev words", [
        "Bhai, GitHub pe mera code push kar de.",
        "VS Code mein yeh file open karo please.",
        "Terminal khol ke npm install chala do.",
        "Yeh bug fix karke ek PR bhej do.",
        "Stack Overflow pe yeh error search karna hai.",
        "VS Code ka theme dark kar do yaar.",
        "Repository clone kar lo apne local mein.",
        "Commit message accha sa likhna, please.",
        "Tests run karo, dekho kya fail ho raha hai.",
        "Branch delete karo, merge ho gaya hai.",
        "Docker container up kar do development wala.",
        "Localhost pe server start karo port three thousand pe.",
        "Merge conflict resolve karna hai, help karo.",
        "Database ka backup le lo aaj raat ko.",
        "API endpoint hit karke response dikhao.",
    ], True),
    (33, "hinglish_office", "Hinglish: office and work", [
        "Boss ko bol do meeting late ho jayegi.",
        "Mail likh do client ko, professional tone mein.",
        "Excel sheet mein data entry kar do.",
        "PPT banao kal ki presentation ke liye.",
        "Calendar pe meeting block karo shaam ko.",
        "Report submit karna hai aaj end of day tak.",
        "LinkedIn pe ek post share karna hai.",
        "Performance review ke liye slides banao.",
        "Team ke saath lunch plan karo, yaar.",
        "Manager ko reminder bhejo stand-up ke liye.",
        "Yeh task Jira pe high priority mark karo.",
        "KPI dashboard update karo is week ka.",
        "Office WiFi ka password kya hai, yaar?",
        "Joining letter draft kar do, please.",
        "Salary slip email kar do HR se mangwa ke.",
    ], True),
    (34, "hinglish_tech_terms", "Hinglish: AI and tech jargon", [
        "Bhai yeh model train karna hai meri awaaz pe.",
        "GPU pe inference chala raha hoon, load zyada hai.",
        "Token count kitna hai is prompt ka?",
        "Embedding vector kaise banate hain, samjhao.",
        "Quantization karne se model fast ho jata hai kya?",
        "Fine tuning ke liye dataset chahiye, kitna?",
        "Loss kam nahi ho raha, learning rate badhao.",
        "Vocabulary size kitna hai is tokenizer ka?",
        "Speech recognition mein WER kaise calculate karte hain?",
        "Latency kam karne ke liye kya karein, bhai?",
        "Batch size badhane se training fast hoti hai kya?",
        "Overfitting ho raha hai, dropout badhao.",
        "Gradient clipping lagao training mein.",
        "Checkpoint save karo har epoch ke baad.",
        "Inference server pe model deploy karo.",
    ], True),

    # ---------------- Hinglish + English code-switching -----------
    (35, "hinglish_english_mix", "Hinglish + English code-switching", [
        "Yaar ek reminder laga do for tomorrow at 5 PM.",
        "Bhai, yeh Slack message forward kar do manager ko.",
        "Mera Zoom call shuru hone wala hai in 5 minutes.",
        "Aaj ek important meeting hai, cancel mat karna please.",
        "GitHub pe mera PR review kar do, urgent hai.",
        "Mummy ko bol do I will be late tonight.",
        "Office se nikalte hain, cab book kar do.",
        "Lunch mein Pizza Hut se order kar lete hain.",
        "Yaar, Netflix pe ek movie suggest karo please.",
        "Mera laptop charge karna hai, charger kidhar hai?",
        "Sunday ko family ke saath dinner plan karte hain.",
        "LinkedIn pe job search kar raha hoon, kuch dikha kya?",
        "Spotify pe lo-fi playlist chala do, study kar raha hoon.",
        "Gym ke baad coffee pe milte hain, chalega?",
        "Bhai ek YouTube video dikhao on how to cook biryani.",
    ], True),
    (36, "hinglish_mid_sentence", "Hinglish words inside English sentences", [
        "Set a reminder for tomorrow yaar.",
        "Book a cab on Ola, please.",
        "Schedule a meeting with the team, boss ko bhi add karna.",
        "Order biryani from Swiggy, extra raita ke saath.",
        "Send a message to my mom on WhatsApp.",
        "Open the door please, yaar.",
        "Find a good restaurant near MG Road.",
        "Take a screenshot of the chart, share karna hai.",
        "Check the weather, thanda hai kya?",
        "Play the next song, yeh achi nahi hai.",
        "Open my Gmail, ek important mail aaya hoga.",
        "Set an alarm for six AM, thak gaya hoon.",
        "Add milk and bread to the shopping list, doodh khatam hai.",
        "Translate this sentence to Hindi, please.",
        "Open the calculator, thoda calculate karna hai.",
    ], True),

    # ---------------- brands (fashion, food, tech) -----------------
    (37, "brands_tech_products", "Tech brand product names", [
        "Buy an iPhone fifteen Pro Max.",
        "Order the MacBook Air M three.",
        "Add a Sony WH-1000XM five to the wish list.",
        "Find a Samsung Galaxy Tab S nine in stock.",
        "Look up the iPad Pro twelve nine inch price.",
        "Order an Apple Watch Series nine.",
        "Find a OnePlus twelve with sixteen gigs of RAM.",
        "Buy a Bose QuietComfort forty five.",
        "Look up the LG OLED C three fifty five inch.",
        "Order a Logitech MX Master three S.",
        "Find a Dyson V fifteen detect in stock.",
        "Add a Kindle Paperwhite to the cart.",
        "Order a GoPro Hero twelve black.",
        "Look up the price of an Alienware m eighteen.",
        "Buy a Raspberry Pi five with eight gigs of RAM.",
    ], False),
    (38, "brands_food_retail", "Food and retail brand names", [
        "Order a Big Mac from McDonald's.",
        "Buy a latte from Starbucks.",
        "Reorder the Amul dark chocolate.",
        "Add a Cadbury celebration box to the cart.",
        "Book a table at Haldiram's for Sunday brunch.",
        "Order a Veg Whopper from Burger King.",
        "Buy a Barilla penne arrabbiata kit.",
        "Reorder our usual Borges olive oil.",
        "Add a Hershey's cookies and cream to the cart.",
        "Find a KFC store near the airport.",
        "Order a Subway footlong veggie delite.",
        "Buy a Baskin Robbins chocolate chip ice cream.",
        "Reorder the Tata Sampann toor dal.",
        "Add a McCain pizza to the cart.",
        "Book a Domino's stuffed crust for tonight.",
    ], False),

    # ---------------- misc complex: legal, philosophy, history ----
    (39, "complex_english_legal", "Complex English: legal terms", [
        "The defendant has the right to remain silent.",
        "File a motion to dismiss the case.",
        "The affidavit must be notarised before submission.",
        "Review the non disclosure agreement before signing.",
        "Schedule a deposition next Thursday at ten AM.",
        "The plaintiff is seeking injunctive relief.",
        "Draft a power of attorney for property matters.",
        "Lodge a complaint with the consumer forum.",
        "Apply for anticipatory bail at the high court.",
        "Serve a legal notice to the defaulter.",
        "The arbitration clause is binding on both parties.",
        "Compute the court fee for this civil suit.",
        "File a public interest litigation in the Supreme Court.",
        "Appeal the lower court's verdict in the appellate tribunal.",
        "Register the trademark with the IP India registry.",
    ], False),
    (40, "complex_english_philosophy", "Complex English: philosophy, literature, history", [
        "The unexamined life is not worth living, said Socrates.",
        "I think therefore I am, said Descartes.",
        "Discuss the central theme of existentialism.",
        "Explain the difference between rationalism and empiricism.",
        "Who wrote the novel One Hundred Years of Solitude?",
        "Summarise the plot of Crime and Punishment in two minutes.",
        "Recite the preamble of the Indian Constitution.",
        "When did India gain independence?",
        "Who was the first president of the United States?",
        "Define the term renaissance in two sentences.",
        "Explain the concept of cognitive dissonance.",
        "Discuss the philosophy of Mahatma Gandhi's satyagraha.",
        "Who wrote the Communist Manifesto?",
        "Summarise the Treaty of Versailles in one minute.",
        "Explain the difference between a meteor and a meteorite.",
    ], False),

    # ---------------- voice assistant specific: wake word + identity -
    (41, "wake_identity", "Wake word and identity confirmation", [
        "Hey Cozy, are you there?",
        "Cozy, what can you do for me?",
        "Hey Cozy, who made you?",
        "Cozy, introduce yourself.",
        "Hey Cozy, what time is it?",
        "Cozy, what's the date today?",
        "Hey Cozy, can you hear me clearly?",
        "Cozy, repeat the last thing you said.",
        "Hey Cozy, are you connected to the internet?",
        "Cozy, what version are you running?",
        "Hey Cozy, are you using my voice model?",
        "Cozy, switch to English mode.",
        "Hey Cozy, switch to Hinglish mode.",
        "Cozy, take a note for me.",
        "Hey Cozy, let's start the day.",
    ], False),

    # ---------------- error recovery: stt failures / repeats -------
    (42, "error_recovery", "Error recovery and repeats", [
        "Sorry, can you repeat that?",
        "I didn't catch that, say it again please.",
        "Cancel that last command.",
        "Never mind, forget what I just said.",
        "Wait, stop the timer.",
        "Sorry, I meant the other one.",
        "No, not that, the one before.",
        "Repeat the last result please.",
        "Speak slower please, I didn't understand.",
        "Wait, I changed my mind, cancel it.",
        "Sorry, wrong command, ignore that.",
        "Yes, that's what I wanted.",
        "No, try again please.",
        "Hmm, that's not right either.",
        "Okay perfect, thank you.",
    ], False),

    # ---------------- Hinglish long, multi-clause -------------------
    (43, "hinglish_long_multi", "Long Hinglish: multi-clause sentences", [
        "Yaar, subah aath baje ki meeting hai toh alarm chhe baje laga dena aur chai bhi ready rakhna please.",
        "Bhai, market jaana hai shaam ko, pehle kapde iron kar do aur grocery list bhi check karna.",
        "Mummy ko bol dena main late hoon aur dinner ke liye guest aa rahe hain toh extra plate rakh lena.",
        "Mujhe Bangalore flight leni hai kal, ticket book kar do shaam wali aur cab bhi book kar lena airport ke liye.",
        "Office jaate waqt bike pe petrol bhar lena aur gym ke bag mein towel aur shoes bharna yaad rakhna.",
        "Bhai, ek project submit karna hai aaj raat tak, mujhe help karna hoga isme, free ho toh message karna.",
        "Yaar, plan cancel karna padega, weather kharab lag raha hai aur tickets ka paisa wapas milega kya check karo.",
        "Papa aaye hain station pe, unhe pickup karna hai aur dinner bahar khaana hai kahin acchi jagah pe book karo.",
        "Mujhe kal subah doctor ke paas jaana hai appointment hai, time yaad dilate rehna aur reports bhi saath leke jaana.",
        "Ghar aake Mummy se kehna chai banana aur Bache ko tayaar karke school bhej do, main office jaldi nikal raha hoon.",
        "Bhai, ek naya phone lena hai 50 hazar ke andar, suggestions de do aur EMI pe lena ho toh wo bhi dekhna.",
        "Yaar shaam ko cricket khelne jaana hai ground pe, saare logo ko message karke confirm kar lena, bat bhi le jaana.",
        "Mujhe ek acchi book chahiye motivation wali, Amazon pe search karke best seller wali order kar do.",
        "Kal anniversary hai, wife ko surprise plan karna hai - restaurant book karo aur cake bhi order kar do, accha sa.",
        "Bhai, ek assignment submit karna hai college mein, deadline kal hai aur main bore ho gaya hoon, help kar do please.",
    ], True),

    # ---------------- fun: small talk, jokes, motivation ------------
    (44, "small_talk_motivation", "Small talk, motivation, jokes", [
        "Tell me a fun fact.",
        "What's the meaning of life in one sentence?",
        "Motivate me for the day.",
        "Tell me a joke about programmers.",
        "What's the best productivity tip you know?",
        "Cheer me up, I'm feeling low.",
        "Give me a quote by Albert Einstein.",
        "Tell me a bedtime story for kids.",
        "What are you grateful for today?",
        "Give me a fun trivia question.",
        "What's the most interesting thing you learned today?",
        "Tell me a tongue twister.",
        "What should I do when I feel overwhelmed?",
        "Sing me a happy birthday song.",
        "Wish my friend happy birthday in a creative way.",
    ], False),
]


# -------------------------------------------------------------- driver
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--replace", action="store_true",
                    help="drop existing sessions with id >= 10 before regenerating")
    ap.add_argument("--per-session", type=int, default=15,
                    help="warn if a session has fewer than this many lines")
    args = ap.parse_args()

    existing = []
    if PROMPTS.exists():
        existing = json.loads(PROMPTS.read_text()).get("sessions", [])

    if args.replace:
        existing = [s for s in existing if s["id"] < 10]
        print(f"--replace: kept sessions {sorted(s['id'] for s in existing)}", flush=True)

    have = {s["id"] for s in existing}
    added = 0
    for sid, name, title, lines, manual in SESSIONS:
        if sid in have:
            print(f"  · session {sid:2d} '{name}' exists, skipping")
            continue
        if len(lines) < args.per_session:
            print(f"  ! session {sid:2d} '{name}' has only {len(lines)} lines "
                  f"(expected {args.per_session})", flush=True)
        existing.append({
            "id": sid,
            "name": name,
            "title": title,
            "manual_only": bool(manual),
            "lines": lines,
        })
        added += 1
        print(f"  + session {sid:2d} '{name}'  ({len(lines)} lines, "
              f"manual_only={bool(manual)})")

    # renumber/keep order
    existing.sort(key=lambda s: s["id"])
    out = {"sessions": existing}
    PROMPTS.write_text(json.dumps(out, indent=2))
    total = sum(len(s["lines"]) for s in existing)
    print(f"\nWrote {PROMPTS}  |  {len(existing)} sessions, {total} lines "
          f"({added} added)")


if __name__ == "__main__":
    main()
